
export const constants = {
  comment: 'Successfully withdraw',
};
export const errorMsg = {
  permissionIssue: `You don't have permission. Contact to Admin`,
  unableFetchBalance: 'Unable to fetch balance',
  burnIssue: 'unable to burn Token ! Try again later.',
  depositIssue: 'unable to Deposit Token ! Try again later',
  noWithdrawList: 'There is no withdrawal list exist',
  noWithdrawData: 'No withdrawal data found',
  invalidToken: 'Invalid token',
  nouserData: "You're not userData",
  noDataFound: ' No data found',
  receiverAddressNotFound: 'Receiver address not found',
  unableToSwap: 'Unable to swap Token. ! Try again later',
  unableToWithdraw: 'Unable to withdraw ! Try again later',
  insufficientFund: 'Insufficient fund',
  tokenNotExist: 'Token does not exists',
  invalidPayload: 'Invalid body payload format',
  txNotFound: 'Transaction details not found',
  somethingWentWrong: 'Something went wrong ! Try again later',
  web3providerUndefined: 'WEB3_PROVIDER not set',
  unableToSendMail: 'Unable To send mail ! Try again later',
  invalidInput: 'Invalid Input',
  passwordConfirmPasswordSame: 'Password and Confirm password should be same',
  passwordChanged: 'Password changed Successfully ! Login now',
  transactionIssue: 'Unable to Swap ! Try again later',
  unableToTransaction: 'Unable to do transaction ! Try again later',
  txFailed: 'Transaction failed. Please contact 1nvest support.',
  amountDecimal: 'Invalid amount',
  ownerBalanceIssue: 'Transaction failed. Please contact 1nvest support.',
};
