name: ci

# Controls when the workflow will run
on:
  pull_request:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up project
        uses: actions/checkout@v2.3.4

      - name: Install Node
        run: |
          npm install
          npm run start
